stages:
  - build
  - deploy

job1:
  stage: build
  tags:
    - easymarket-java
  only:
    - master
  script:
    - mvn clean package
    - scp ./target/easymarket-0.0.1-SNAPSHOT.jar root@116.85.15.199:/home/easymarket

job2:
  stage: deploy
  tags:
    - easymarket-java
  only:
    - master
  script:
    - ssh root@116.85.15.199 "sh /home/easymarket/shutdown.sh; sh /home/easymarket/startup.sh"