stages:
  - build
  - deploy

job1:
  stage: build
  tags:
    - easymarket-java
  only:
    - master
  script:
    - mvn clean package

job2:
  stage: deploy
  tags:
    - easymarket-java
  only:
    - master
  script:
    - echo "am"