stages:
  - build
  - deploy

job1:
  stage: build
  tags:
    - easymarket-java
  only:
    - master
  script:
    - mvn clean package
    - echo `pwd`
    - cp ./target/easymarket-0.0.1-SNAPSHOT.jar /opt

job2:
  stage: deploy
  tags:
    - easymarket-java
  only:
    - master
  script:
    - echo "am"